services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code/
      - static_volume:/code/staticfiles
    networks:
      - tinyurl_network
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    depends_on:
      - db
    restart: "on-failure"
  db:
    image: library/postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - tinyurl_network
    env_file:
      - ./envs/.env.db

volumes:
  postgres_data:
  static_volume:

networks:
  tinyurl_network:
    driver: bridge