# Generated by Django 3.2.9 on 2021-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='token',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
